[workspace]
resolver = "2"
default-members = [
    "services/bartender",
]
members = [
    "middlewares/jwt",
    "libs/logger",
    "services/bartender",
    "services/example",
]

[workspace.dependencies]
jwt = { path = "middlewares/jwt" }
logger = { path = "libs/logger" }
