[package]
name = "jwt"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
serde = { version = "1.0.203", features = ["derive"] }
chrono = "0.4.38"
jsonwebtoken = "9.2.0"
async-trait = "0.1.80"
http = "1.1.0"
serde_json = "1.0.117"
lazy_static = "1.4.0"
log = "0.4.21"
